export const SET_PRIMARY_VALUE = "mobile/ledger/SET_PRIMARY_VALUE";
export const SET_ACCOUNT_INPUT = "mobile/ledger/SET_ACCOUNT_INPUT";

export const GET_FISCAL_YEARS_REQUEST =
  "mobile/ledger/GET_FISCAL_YEARS_REQUEST";
export const GET_FISCAL_YEARS_SUCCESS =
  "mobile/ledger/GET_FISCAL_YEARS_SUCCESS";
export const GET_FISCAL_YEARS_FAILURE =
  "mobile/ledger/GET_FISCAL_YEARS_FAILURE";

export const GET_LEDGER_LIST_HEADERS_REQUEST =
  "mobile/ledger/GET_LEDGER_LIST_HEADERS_REQUEST";
export const GET_LEDGER_LIST_HEADERS_SUCCESS =
  "mobile/ledger/GET_LEDGER_LIST_HEADERS_SUCCESS";
export const GET_LEDGER_LIST_HEADERS_FAILURE =
  "mobile/ledger/GET_LEDGER_LIST_HEADERS_FAILURE";

export const LOAD_ACCOUNT_LEDGER_REQUEST =
  "mobile/ledger/LOAD_ACCOUNT_LEDGER_REQUEST";
export const LOAD_ACCOUNT_LEDGER_SUCCESS =
  "mobile/ledger/LOAD_ACCOUNT_LEDGER_SUCCESS";
export const LOAD_ACCOUNT_LEDGER_FAILURE =
  "mobile/ledger/LOAD_ACCOUNT_LEDGER_FAILURE";

export const LOAD_ACCOUNT_NAMES_REQUEST =
  "mobile/ledger/LOAD_ACCOUNT_NAMES_REQUEST";
export const LOAD_ACCOUNT_NAMES_SUCCESS =
  "mobile/ledger/LOAD_ACCOUNT_NAMES_SUCCESS";
export const LOAD_ACCOUNT_NAMES_FAILURE =
  "mobile/ledger/LOAD_ACCOUNT_NAMES_FAILURE";

export const GET_LEDGER_LIST_REQUEST = "mobile/ledger/GET_LEDGER_LIST_REQUEST";
export const GET_LEDGER_LIST_SUCCESS = "mobile/ledger/GET_LEDGER_LIST_SUCCESS";
export const GET_LEDGER_LIST_FAILURE = "mobile/ledger/GET_LEDGER_LIST_FAILURE";
